### ISSUE TITLE
ES Modules

### ISSUE THREAD

**Issue by kennetpostigo** [rrdelaney/bs-loader#1]
I see that in your implementation you hard coded the loader to look for lib js however in order to take advantage of tree shaking we must tell bs to not use commonjs and instead use es6. Would it be possible for you to check the bsconfig field package-specs for es6? There are several other module formats and bs makes separate folders for these.

**Comment by rrdelaney** [comment]
I didn't know `bsb` could output ES Modules. How do you configure it that way?

I'll also add a loader option to set the module directory to use.

**Comment by rrdelaney** [comment]
As of version 1.1.1 (b5dbd302ed232dca4ded683e13c0960ddc1a5312) you can now add a `module` option to the loader to specify what module type to look for. For example, if you wanted to use the AMD modules generated by `bsb`: 

```js
rules: [
      { test: /.(re|ml)$/, use: 'bs-loader?module=amd' },
]
```

bs-loader will then look at `lib/amd` for JS files to load. Does this satisfy the use case for ES Modules?

**Comment by kennetpostigo** [comment]
Thank you @rrdelaney ! so does this mean all 
i would have to do for es modules is: rules: [
      { test: /.(re|ml)$/, use: 'bs-loader?module=es6' },
]

**Comment by rrdelaney** [comment]
I've never output ES Modules with bucklescript, but if the output directory looks like 'lib/es6' then that will do the trick!

**Comment by kennetpostigo** [comment]
Awesome thanks @rrdelaney !

**Comment by rrdelaney** [comment]
Is it ok to close this issue now?
