### ISSUE TITLE
Error running jest on fresh clone without building first

### ISSUE THREAD

**Issue by glennsl** [rrdelaney/bs-loader#13]
Error is:
```
Cannot find module '../src/jest.js' from 'expect_test.js'
```
and so on for each test file.

repro script:
```
git clone https://github.com/buckletypes/bs-jest
cd bs-jest
git checkout bs-loader
npm link bs-platform
npm i
node_modules/jest/bin/jest.js
```

Workaround is to just add `bsb -make-world &&` before `jest` in the appropriate npm scripts

**Comment by rrdelaney** [comment]
This applied to the whole project in general, including Webpack builds 😕

**Comment by rrdelaney** [comment]
This is fixed when using `npm link bs-platform` 😄
