### ISSUE TITLE
Webpack can't resolve compiled dependencies

### ISSUE THREAD

**Issue by alexfedoseev** [rrdelaney/bs-loader#4]
I just tried this loader and it doesn't work. When the loader internally triggers `bsb` and it compiles `re` module, which contains dependency, loader returns string with `require`d js dependency, but webpack can't resolve it as its context is in `src` folder (where `re` module resides), but not in output `lib/js` folder.

**Comment by rrdelaney** [comment]
I recommend using a separate modules directory when requiring non-bucklescript files. See the documentation on [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules). This lets you still require JS files, just not co-located with your Reason or OCaml files.

**Comment by alexfedoseev** [comment]
Hm this issue is about bs files only, I actually used files from your example.

**Comment by alexfedoseev** [comment]
I'll try to elaborate.

This is `src` from the example:

```
| -- src/
    |-- fib.re
    |-- print.re
```

```re
/* print.re */
Js.log (Fib.fib 10);
```

^ This what loader receives. Internally loader passes it to `bsb` and it compiles it to:

```js
...
var Fib = require('./fib.js');
...
```

This output as a string is passed from loader to webpack, but webpack is dealing w/ `src/print.re` and looking for `'./fib.js'` in `src` folder (it expects`fib.js` to be right next to `src/print.re`, not in `lib/js` one).

**Comment by rrdelaney** [comment]
Can you please paste your webpack config and bucklescript config?

**Comment by alexfedoseev** [comment]
Sure, here is the repo to reproduce: https://github.com/alexfedoseev/bs-loader-issue

Output:

<img width="905" alt="screen shot 2017-04-24 at 13 55 32" src="https://cloud.githubusercontent.com/assets/4244251/25324177/e71bd5a6-28f6-11e7-9545-9f0ad083f376.png">

**Comment by rrdelaney** [comment]
Looks like the newer version of Bucklescript broke this! I was using 1.5 on my example, but as soon as I installed 1.7 it started to repro your issue. I'll look further into this now that I know what the problem is.

**Comment by rrdelaney** [comment]
Looks like the problem was created in the Bucklescript 1.6.1 release with this issue: https://github.com/bloomberg/bucklescript/issues/1465. I'll try to look more into this when I get the time, but the fix will probably be on the Bucklescript side.

**Comment by alexfedoseev** [comment]
Looks like with 1.5 when webpack receives `require('./foo')`, it resolves `src/foo.re` and it most likely causes double compilation work as `src/foo.re` was already compiled by `bsb` when it dealt `src/app.re`. It might be significant overhead w/ big dependency tree.

**Comment by rrdelaney** [comment]
The double compilation overhead was pretty small when I was first testing this, `bsb` seemed to cache pretty well. Haven't done it with a large codebase though.

**Comment by alexfedoseev** [comment]
Good to know! I also tried to switch the context of the file inside the loader so webpack can resolve already compiled files, but looks like webpack doesn't allow this. And most likely it will cause issues w/ `watch` mode.

**Comment by rrdelaney** [comment]
I make a pretty hacky fix in b81575289600bf69ca94c47aec60a041e588d95c and published version 1.2 to npm. Can you see if that works for you?

**Comment by alexfedoseev** [comment]
Works, thanks! Should I close this?

**Comment by rrdelaney** [comment]
Yep, re-open it if 1.2 is buggy for whatever reason!
