### ISSUE TITLE
webpack --watch ignores changes in local dependencies after receiving syntax error there

### ISSUE THREAD

**Issue by garkin** [rrdelaney/bs-loader#8]
https://github.com/garkin/bs_loader_webpack_watch_bug

### Steps to reproduce

1. `git clone https://github.com/garkin/bs_loader_webpack_watch_bug`
2. `npm install`
3. `npm start` to start watching using webpack
4. Uncomment `some syntax error` line in the `src/fib.re` to break program and get an error
5. Comment back `some syntax error` line in the `src/fib.re` to restore program correctness 

### Expected behavior:
After removing error in `src/fib.re` - changes are recompiled and we get console output about succesfull recompilation.

### Actual behavior:
(5.) and further `src/fib.re` changes are not recompiled and we do not get updates in the console.
But changes in the entry `src/index.re` do trigger correct recompilation.

### Environment:
```
Windows 10 
NodeJS v6.9.1

Centos 7
Linux 3.18.17-13.el7.x86_64
NodeJS v6.10.3

"bs-loader": "1.2.5"
"bs-platform": "1.7.4"
"reason-js": "0.3.0"
"webpack": "2.6.1"
```

**Comment by garkin** [comment]
My bad. It actually ignore changes after error in ANY file. 
Even in entry.

**Comment by rrdelaney** [comment]
Can you paste your entire webpack config?

**Comment by garkin** [comment]
https://github.com/garkin/bs_loader_webpack_watch_bug/blob/master/webpack.config.js

**Comment by rrdelaney** [comment]
Try adding "errorType: warning" to the loader options

**Comment by garkin** [comment]
After adding:
```
use: { loader: 'bs-loader', options: { module: 'es6', errorType: "warning" } }"
```
Watching is working as intended, but there are no error output in the console at all.

**Comment by rrdelaney** [comment]
Does running "bsb-w" work for you?

**Comment by garkin** [comment]
Yes, `bsb - w` working.

**Comment by rrdelaney** [comment]
Hmm. This is definitely weird. I think it might be an issue using this with Windows.

I can't look too much into it right now, but I'll check it out later.

**Comment by garkin** [comment]
This is not Windows issue. I can reproduce it on CentOS.

**Comment by rrdelaney** [comment]
Thanks so much for trying again on another OS! That makes it easier for me to test 😄

**Comment by rrdelaney** [comment]
This is 100% not a Windows issue, thanks so much for proving an example repo where the issue can be seen! I'm working on this now

**Comment by rrdelaney** [comment]
Try out version `1.3.0` just published on npm 😃

**Comment by garkin** [comment]
Thank you, it's now fixed.

**Comment by rrdelaney** [comment]
Hey! Thanks for submitting this issue 😄Reason-Scripts will automatically run "npm link bs-platform" upon install.
